### ISSUE TITLE
define ... and union of function and variable namespace

### ISSUE THREAD

**Issue by charJe** [chebert/schemeish#4]
It seems that in contrast to the readme (and scheme), `define` can only be used to define functions. 
the `(define symbol form)` version of define is expecting `form` to resolve to a function. I expect this to act just like the readme and scheme such that I can `(define four 4)`.

---

This maybe should be a separate issue, but it is related to define. I know you have the `[]`, but I honestly find it kind of unsatisfying. Even when programming Racket, I never use `[]` or `{}`. As an alternative, I thought, since, schemeish is providing `define`, `let`, and `lambda`, it could force a shared namespace. For defining values, if the value of a binding is a function, then also locally bind the fdefinition (I'm not sure how to do this). For defining functions, also locally bind the value of the symbol to the function.

This should allow something like this
```scheme
(define (test)
  (let ((exclaim (lambda (string)
                  (concatenate 'string string "!"))))
    (exclaim "test")))
;; As a side-note here, it would be nice to have `letrec` that defines functions (but not values) in a `labels` form.
```

This would not interfere with higher order functions.
```scheme
(define (add1 x)
  (+ x 1))
(map 'add1 (list 1 2 3))
```
but would allow the omission of the quote because the function add1 is also stored in the value slot of the add1 symbol.
```scheme
(map add1 (list 1 2 3))
```

**Warning: possible sacrilege**
One hiccup is that not all functions and global constants are made with `define`. I'm particularly thinking of the common-lisp package and libraries. For these cases there can be a funtion that will unify the two name spaces (go through all external symbols and define functions in the value namespace and vice versa) leaving any conflicts separated.

**Comment by chebert** [comment]
In order to support global lexical environment I would need to modify the way the evaluator works.

My goal is to just have drop-in scheme style syntax that doesn't conflict with Common Lisp, so this is off the table.

The readme should be updated though. Top level defines should only define functions. This is good because it introduces simple syntax for defining computed functions:

`(define 2+ (lcurry #'+ 2))`

`[...]` is just syntactic sugar for `(funcall ...)`. There's no reason that one has to use it (or even install it in the read table). I agree that it isn't the same as scheme, but functions having a namespace means defmacro works well.

**Comment by chebert** [comment]
I ended up coming around on this with the SCM/DEF macros. 
The SCM macro does code-walking to transform function applications from (function args...) to (funcall function args...)
and symbols which are not special or lexically bound are from symbol to (function symbol).

Unfortunately it's dependent on the non-ANSI CLTL2 VARIABLE-INFORMATION function to determine if a name is lexically scoped.
